# Python Numpy Exercises

In [2]:
import numpy as np

In [3]:
rez = np.array([3,5,7,9])
print(rez)

[3 5 7 9]


In [4]:
rez1 = np.array([10,2,12,32,43,5,8,11,3,5,7,9,23,54,87,9,20,14,56,10,11])

In [5]:
rez1.shape

(21,)

In [6]:
rez1_rs = rez1.reshape(3,7) #Reshape the array

In [7]:
print(rez1_rs)

[[10  2 12 32 43  5  8]
 [11  3  5  7  9 23 54]
 [87  9 20 14 56 10 11]]


In [8]:
print("Shape of rez1_rs(row,column) : ", rez1_rs.shape)

Shape of rez1_rs(row,column) :  (3, 7)


In [9]:
print("Dimension of rez1_rs: ",rez1_rs.ndim)

Dimension of rez1_rs:  2


In [10]:
zero_rez= np.zeros((5,5))


In [11]:
print(zero_rez)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
zero_rez[2,2] = 1

In [13]:
print(zero_rez)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
print(zero_rez.reshape(1,25))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]


In [15]:
np.empty((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
rez3= np.arange(3,39,3)

In [17]:
print(rez3)

[ 3  6  9 12 15 18 21 24 27 30 33 36]


In [18]:
rez3.shape

(12,)

In [19]:
rez3.reshape((4,3))

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27],
       [30, 33, 36]])

In [22]:
array1= np.array([1,3,5,7,9])
array2= np.array([2,4,6,8,10])

In [26]:
print(array1+array2)
print(array1-array2)
print(array1*array2)

[ 3  7 11 15 19]
[-1 -1 -1 -1 -1]
[ 2 12 30 56 90]


.

### Array Printing Options/Operations ###

.

In [33]:
rez = np.array([[2,9,3,8],[4,7,5,6]])

In [34]:
print(rezi)

[[2 9 3 8]
 [4 7 5 6]]


In [35]:
print(rez[1,3]) 

6


In [36]:
print(rez[1,:]) #2.row's all elements.

[4 7 5 6]


In [38]:
print(rez[:,1]) #All elements of 2.column

[9 7]


In [39]:
print(rez[-1,:]) #Last row's all columns

[4 7 5 6]


In [40]:
print(rez[:,-1]) #Last column's all rows

[8 6]


# 

In [41]:
rez = np.array([1,2,3,4,5,6,7,8,9])

In [49]:
rez_rs = rez.reshape(3,3)
print(rez_rs)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
rez_rs.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])