# Python Numpy Exercises

In [9]:
import numpy as np

In [10]:
rez = np.array([3,5,7,9])
print(rez)

[3 5 7 9]


In [11]:
rez1 = np.array([10,2,12,32,43,5,8,11,3,5,7,9,23,54,87,9,20,14,56,10,11])

In [12]:
rez1.shape

(21,)

In [13]:
rez1_rs = rez1.reshape(3,7) #Reshape the array

In [14]:
print(rez1_rs)

[[10  2 12 32 43  5  8]
 [11  3  5  7  9 23 54]
 [87  9 20 14 56 10 11]]


In [15]:
print("Shape of rez1_rs(row,column) : ", rez1_rs.shape)

Shape of rez1_rs(row,column) :  (3, 7)


In [16]:
print("Dimension of rez1_rs: ",rez1_rs.ndim)

Dimension of rez1_rs:  2


In [17]:
zero_rez= np.zeros((5,5))


In [18]:
print(zero_rez)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
zero_rez[2,2] = 1

In [20]:
print(zero_rez)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
print(zero_rez.reshape(1,25))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]


In [22]:
np.empty((6,6))

array([[1.25504833e-311, 1.19069821e-321, 0.00000000e+000,
        0.00000000e+000, 1.29699722e-085, 1.16097020e-028],
       [1.26087994e-076, 2.54867590e-028, 1.72291444e-047,
        1.04917183e-153, 5.23081515e-143, 2.35825918e+184],
       [8.00551651e+169, 9.50156306e+169, 4.39259757e+175,
        5.19189705e-144, 3.59751658e+252, 1.46901661e+179],
       [8.37404147e+242, 4.31999013e-096, 4.82337723e+228,
        1.31343221e-047, 1.68503993e+160, 5.49703413e-090],
       [1.11597048e-046, 8.07624965e+169, 5.04621343e+180,
        1.94918963e-153, 5.45645596e-066, 2.34153152e-057],
       [1.54772934e+185, 8.37947430e+165, 1.04914908e-153,
        9.08366791e+223, 5.82381891e-144, 1.68054251e-094]])

In [23]:
rez3= np.arange(3,39,3)

In [24]:
print(rez3)

[ 3  6  9 12 15 18 21 24 27 30 33 36]


In [25]:
rez3.shape

(12,)

In [26]:
rez3.reshape((4,3))

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27],
       [30, 33, 36]])

In [27]:
array1= np.array([1,3,5,7,9])
array2= np.array([2,4,6,8,10])

In [28]:
print(array1+array2)
print(array1-array2)
print(array1*array2)

[ 3  7 11 15 19]
[-1 -1 -1 -1 -1]
[ 2 12 30 56 90]


.

### Array Printing Options/Operations ###

.

In [29]:
rez = np.array([[2,9,3,8],[4,7,5,6]])

In [31]:
print(rez)

[[2 9 3 8]
 [4 7 5 6]]


In [ ]:
print(rez[1,3]) 

In [ ]:
print(rez[1,:]) #2.row's all elements.

In [ ]:
print(rez[:,1]) #All elements of 2.column

In [ ]:
print(rez[-1,:]) #Last row's all columns

In [ ]:
print(rez[:,-1]) #Last column's all rows

# 

In [ ]:
rez = np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
rez_rs = rez.reshape(3,3)
print(rez_rs)

In [ ]:
rez_rs.T